# We follow the versioning of Cities Skylines
version: 1.1.0.{build}

configuration: Release

cache:
  - packages -> appveyor\packages.config

build_script:
  - ps: appveyor\Build.ps1

artifacts:
  - path: bin
    name: ScrollableToolbar-v$(appveyor_build_version)
    type: zip
  - path: workshop
    name: ScrollableToolbar-workshop-v$(appveyor_build_version)
    type: zip
